// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDapazSdFDu6gUoxkanwlPIsObZaswgaHs',
    appId: '1:262062531800:android:acfcd36e7ea544b77063ad',
    messagingSenderId: '262062531800',
    projectId: 'mystictodolist',
    storageBucket: 'mystictodolist.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCztvE11kH8yFT1EKpzb_MPxNULCsQDIRQ',
    appId: '1:262062531800:ios:6be0a261bc8292807063ad',
    messagingSenderId: '262062531800',
    projectId: 'mystictodolist',
    storageBucket: 'mystictodolist.appspot.com',
    androidClientId: '262062531800-7tstrv243gd9pobasec6jjd3q6th26mi.apps.googleusercontent.com',
    iosClientId: '262062531800-7qat36tgu09o8ivn6kn8279qukovvlor.apps.googleusercontent.com',
    iosBundleId: 'com.example.mysticTodo',
  );

}